test:
  restrict_domain: "example.com"
  mailer:
    from: 'test@example.com'

development:
  placeholder: 1
  mailer:
    from: 'test@example.com'

production: <%= Apohypaton::Kv.load_secret('secrets', true) %> 
